/**
 * WikiMasters Web Dashboard - Données de Démonstration & Moteur de Simulation
 * Thème : Deep Cyber & Gemstones
 * Fournit un jeu complet de données réalistes pour le fonctionnement autonome du dashboard
 */

export const OFFICIAL_RARITIES = {
  L: {
    id: 'L',
    key: 'LEGENDARY',
    label: 'Légendaire',
    shortCode: 'L',
    color: '#ffe144',
    textColor: '#0d1117',
    bgColor: 'rgba(255, 225, 68, 0.15)',
    borderColor: '#ffe144',
    glowColor: 'rgba(255, 225, 68, 0.4)'
  },
  UR: {
    id: 'UR',
    key: 'ULTRA_RARE',
    label: 'Ultra Rare',
    shortCode: 'UR',
    color: '#fa9931',
    textColor: '#ffffff',
    bgColor: 'rgba(250, 153, 49, 0.15)',
    borderColor: '#fa9931',
    glowColor: 'rgba(250, 153, 49, 0.4)'
  },
  SR: {
    id: 'SR',
    key: 'SUPER_RARE',
    label: 'Super Rare',
    shortCode: 'SR',
    color: '#ed6fa3',
    textColor: '#ffffff',
    bgColor: 'rgba(237, 111, 163, 0.15)',
    borderColor: '#ed6fa3',
    glowColor: 'rgba(237, 111, 163, 0.4)'
  },
  R: {
    id: 'R',
    key: 'RARE',
    label: 'Rare',
    shortCode: 'R',
    color: '#c6a7f2',
    textColor: '#0d1117',
    bgColor: 'rgba(198, 167, 242, 0.15)',
    borderColor: '#c6a7f2',
    glowColor: 'rgba(198, 167, 242, 0.4)'
  },
  PC: {
    id: 'PC',
    key: 'UNCOMMON',
    label: 'Peu Commune',
    shortCode: 'PC',
    color: '#b1cff2',
    textColor: '#0d1117',
    bgColor: 'rgba(177, 207, 242, 0.15)',
    borderColor: '#b1cff2',
    glowColor: 'rgba(177, 207, 242, 0.4)'
  },
  C: {
    id: 'C',
    key: 'COMMON',
    label: 'Commune',
    shortCode: 'C',
    color: '#b8f2d5',
    textColor: '#0d1117',
    bgColor: 'rgba(184, 242, 213, 0.15)',
    borderColor: '#b8f2d5',
    glowColor: 'rgba(184, 242, 213, 0.4)'
  }
};

export const INITIAL_MOCK_CARDS = [
  {
    id: 'card_demo_01',
    boosterId: 'booster_demo_01',
    sessionId: 'session_demo_01',
    name: 'Adèle Castillon',
    rarity: 'L',
    rarityLabel: 'Légendaire',
    rarityShortCode: 'L',
    rarityColor: '#ffe144',
    cardIndex: 5,
    totalInBooster: 5,
    description: 'Chanteuse, actrice et vidéaste française. Membre emblématique du duo Vidéoclub, figure majeure de la pop synthwave.',
    attack: 94,
    defense: 88,
    avgPrice: 2850,
    minPrice: 2400,
    maxPrice: 3200,
    lastPrice: 2900,
    sellPriceMin: 1425,
    sellPriceMax: 2138,
    sellPriceMid: 1781,
    salesCount: 14,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (4 * 86400000 + 1000 * 60 * 180)
  },
  {
    id: 'card_demo_02',
    boosterId: 'booster_demo_01',
    sessionId: 'session_demo_01',
    name: 'Albert Einstein',
    rarity: 'UR',
    rarityLabel: 'Ultra Rare',
    rarityShortCode: 'UR',
    rarityColor: '#fa9931',
    cardIndex: 4,
    totalInBooster: 5,
    description: 'Physicien théoricien germano-américain, auteur de la théorie de la relativité restreinte et générale. Prix Nobel de physique 1921.',
    attack: 85,
    defense: 92,
    avgPrice: 1450,
    minPrice: 1200,
    maxPrice: 1700,
    lastPrice: 1500,
    sellPriceMin: 725,
    sellPriceMax: 1088,
    sellPriceMid: 906,
    salesCount: 22,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (4 * 86400000 + 1000 * 60 * 179)
  },
  {
    id: 'card_demo_03',
    boosterId: 'booster_demo_01',
    sessionId: 'session_demo_01',
    name: 'Marie Curie',
    rarity: 'UR',
    rarityLabel: 'Ultra Rare',
    rarityShortCode: 'UR',
    rarityColor: '#fa9931',
    cardIndex: 3,
    totalInBooster: 5,
    description: 'Physicienne et chimiste polonaise naturalisée française, double lauréate du prix Nobel (Physique 1903, Chimie 1911).',
    attack: 82,
    defense: 90,
    avgPrice: 1120,
    minPrice: 950,
    maxPrice: 1300,
    lastPrice: 1100,
    sellPriceMin: 560,
    sellPriceMax: 840,
    sellPriceMid: 700,
    salesCount: 19,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (4 * 86400000 + 1000 * 60 * 178)
  },
  {
    id: 'card_demo_04',
    boosterId: 'booster_demo_01',
    sessionId: 'session_demo_01',
    name: 'Tour Eiffel',
    rarity: 'SR',
    rarityLabel: 'Super Rare',
    rarityShortCode: 'SR',
    rarityColor: '#ed6fa3',
    cardIndex: 2,
    totalInBooster: 5,
    description: 'Monument emblématique de Paris érigé par Gustave Eiffel pour l\'Exposition universelle de 1889. Hauteur 330 mètres.',
    attack: 78,
    defense: 84,
    avgPrice: 420,
    minPrice: 380,
    maxPrice: 510,
    lastPrice: 430,
    sellPriceMin: 210,
    sellPriceMax: 315,
    sellPriceMid: 263,
    salesCount: 45,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (4 * 86400000 + 1000 * 60 * 177)
  },
  {
    id: 'card_demo_05',
    boosterId: 'booster_demo_01',
    sessionId: 'session_demo_01',
    name: 'Léonard de Vinci',
    rarity: 'L',
    rarityLabel: 'Légendaire',
    rarityShortCode: 'L',
    rarityColor: '#ffe144',
    cardIndex: 1,
    totalInBooster: 5,
    description: 'Polymathe italien de la Renaissance, peintre de la Joconde et génie universel précurseur des sciences et inventions modernes.',
    attack: 95,
    defense: 91,
    avgPrice: 3100,
    minPrice: 2800,
    maxPrice: 3600,
    lastPrice: 3200,
    sellPriceMin: 1550,
    sellPriceMax: 2325,
    sellPriceMid: 1938,
    salesCount: 8,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (4 * 86400000 + 1000 * 60 * 176)
  },
  {
    id: 'card_demo_06',
    boosterId: 'booster_demo_02',
    sessionId: 'session_demo_02',
    name: 'Système Solaire',
    rarity: 'SR',
    rarityLabel: 'Super Rare',
    rarityShortCode: 'SR',
    rarityColor: '#ed6fa3',
    cardIndex: 5,
    totalInBooster: 5,
    description: 'Système planétaire composé d\'une étoile centrale, le Soleil, et des huit planètes orbitant autour de son champ gravitationnel.',
    attack: 74,
    defense: 89,
    avgPrice: 380,
    minPrice: 320,
    maxPrice: 440,
    lastPrice: 375,
    sellPriceMin: 190,
    sellPriceMax: 285,
    sellPriceMid: 238,
    salesCount: 31,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (3 * 86400000 + 1000 * 60 * 140)
  },
  {
    id: 'card_demo_07',
    boosterId: 'booster_demo_02',
    sessionId: 'session_demo_02',
    name: 'Pyramide de Khéops',
    rarity: 'R',
    rarityLabel: 'Rare',
    rarityShortCode: 'R',
    rarityColor: '#c6a7f2',
    cardIndex: 4,
    totalInBooster: 5,
    description: 'Plus grande pyramide de Gizeh, édifiée sous la IVe dynastie pour le pharaon Khéops. Unique des Sept Merveilles encore debout.',
    attack: 68,
    defense: 88,
    avgPrice: 180,
    minPrice: 150,
    maxPrice: 210,
    lastPrice: 185,
    sellPriceMin: 90,
    sellPriceMax: 135,
    sellPriceMid: 113,
    salesCount: 52,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (3 * 86400000 + 1000 * 60 * 139)
  },
  {
    id: 'card_demo_08',
    boosterId: 'booster_demo_02',
    sessionId: 'session_demo_02',
    name: 'Loup Gris',
    rarity: 'PC',
    rarityLabel: 'Peu Commune',
    rarityShortCode: 'PC',
    rarityColor: '#b1cff2',
    cardIndex: 3,
    totalInBooster: 5,
    description: 'Canidé sauvage carnivore, prédateur alpha vivant et chassant en meute organisée dans l\'hémisphère nord.',
    attack: 65,
    defense: 58,
    avgPrice: 65,
    minPrice: 50,
    maxPrice: 85,
    lastPrice: 60,
    sellPriceMin: 32,
    sellPriceMax: 49,
    sellPriceMid: 40,
    salesCount: 88,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (3 * 86400000 + 1000 * 60 * 138)
  },
  {
    id: 'card_demo_09',
    boosterId: 'booster_demo_02',
    sessionId: 'session_demo_02',
    name: 'Chêne Pédonculé',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 2,
    totalInBooster: 5,
    description: 'Arbre à feuilles caduques des forêts tempérées d\'Europe, symbole séculaire de force, majesté et longévité.',
    attack: 30,
    defense: 72,
    avgPrice: 25,
    minPrice: 15,
    maxPrice: 35,
    lastPrice: 20,
    sellPriceMin: 12,
    sellPriceMax: 19,
    sellPriceMid: 15,
    salesCount: 140,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (3 * 86400000 + 1000 * 60 * 137)
  },
  {
    id: 'card_demo_10',
    boosterId: 'booster_demo_02',
    sessionId: 'session_demo_02',
    name: 'Vase d\'Anduze',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 1,
    totalInBooster: 5,
    description: 'Poterie traditionnelle cévenole en terre cuite flammée, réputée depuis le XVIIe siècle pour abriter les orangers.',
    attack: 20,
    defense: 60,
    avgPrice: 18,
    minPrice: 10,
    maxPrice: 25,
    lastPrice: 15,
    sellPriceMin: 9,
    sellPriceMax: 14,
    sellPriceMid: 11,
    salesCount: 175,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (3 * 86400000 + 1000 * 60 * 136)
  },
  {
    id: 'card_demo_11',
    boosterId: 'booster_demo_03',
    sessionId: 'session_demo_03',
    name: 'Jeanne d\'Arc',
    rarity: 'SR',
    rarityLabel: 'Super Rare',
    rarityShortCode: 'SR',
    rarityColor: '#ed6fa3',
    cardIndex: 5,
    totalInBooster: 5,
    description: 'Héroïne de l\'histoire de France, cheffe de guerre et sainte patronne ayant mené les troupes royales durant la guerre de Cent Ans.',
    attack: 86,
    defense: 80,
    avgPrice: 560,
    minPrice: 490,
    maxPrice: 680,
    lastPrice: 570,
    sellPriceMin: 280,
    sellPriceMax: 420,
    sellPriceMid: 350,
    salesCount: 38,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (2 * 86400000 + 1000 * 60 * 95)
  },
  {
    id: 'card_demo_12',
    boosterId: 'booster_demo_03',
    sessionId: 'session_demo_03',
    name: 'Alexandre le Grand',
    rarity: 'UR',
    rarityLabel: 'Ultra Rare',
    rarityShortCode: 'UR',
    rarityColor: '#fa9931',
    cardIndex: 4,
    totalInBooster: 5,
    description: 'Roi de Macédoine et conquérant de l\'Empire perse, l\'un des plus illustres stratèges militaires de l\'Antiquité.',
    attack: 90,
    defense: 85,
    avgPrice: 1350,
    minPrice: 1100,
    maxPrice: 1600,
    lastPrice: 1400,
    sellPriceMin: 675,
    sellPriceMax: 1013,
    sellPriceMid: 844,
    salesCount: 16,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (2 * 86400000 + 1000 * 60 * 94)
  },
  {
    id: 'card_demo_13',
    boosterId: 'booster_demo_03',
    sessionId: 'session_demo_03',
    name: 'Nébuleuse d\'Orion',
    rarity: 'R',
    rarityLabel: 'Rare',
    rarityShortCode: 'R',
    rarityColor: '#c6a7f2',
    cardIndex: 3,
    totalInBooster: 5,
    description: 'Nébuleuse en émission diffuse située au cœur de la constellation d\'Orion, véritable pouponnière stellaire à 1344 années-lumière.',
    attack: 70,
    defense: 80,
    avgPrice: 210,
    minPrice: 180,
    maxPrice: 260,
    lastPrice: 220,
    sellPriceMin: 105,
    sellPriceMax: 158,
    sellPriceMid: 131,
    salesCount: 39,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (2 * 86400000 + 1000 * 60 * 93)
  },
  {
    id: 'card_demo_14',
    boosterId: 'booster_demo_03',
    sessionId: 'session_demo_03',
    name: 'Renard Roux',
    rarity: 'PC',
    rarityLabel: 'Peu Commune',
    rarityShortCode: 'PC',
    rarityColor: '#b1cff2',
    cardIndex: 2,
    totalInBooster: 5,
    description: 'Mammifère carnivore opportuniste réputé pour sa ruse et son remarquable pouvoir d\'adaptation géographique.',
    attack: 60,
    defense: 55,
    avgPrice: 55,
    minPrice: 40,
    maxPrice: 75,
    lastPrice: 50,
    sellPriceMin: 28,
    sellPriceMax: 41,
    sellPriceMid: 34,
    salesCount: 95,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (2 * 86400000 + 1000 * 60 * 92)
  },
  {
    id: 'card_demo_15',
    boosterId: 'booster_demo_03',
    sessionId: 'session_demo_03',
    name: 'Galet du Rhône',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 1,
    totalInBooster: 5,
    description: 'Fragment minéral poli par les courants alluviaux fluviaux, typique des terroirs viticoles de Châteauneuf-du-Pape.',
    attack: 15,
    defense: 75,
    avgPrice: 15,
    minPrice: 8,
    maxPrice: 20,
    lastPrice: 12,
    sellPriceMin: 8,
    sellPriceMax: 11,
    sellPriceMid: 9,
    salesCount: 210,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (2 * 86400000 + 1000 * 60 * 91)
  },
  {
    id: 'card_demo_16',
    boosterId: 'booster_demo_04',
    sessionId: 'session_demo_04',
    name: 'Aurore Polaire',
    rarity: 'SR',
    rarityLabel: 'Super Rare',
    rarityShortCode: 'SR',
    rarityColor: '#ed6fa3',
    cardIndex: 5,
    totalInBooster: 5,
    description: 'Phénomène lumineux atmosphérique céleste provoqué par l\'interaction des particules solaires chargées avec la magnétosphère terrestre.',
    attack: 68,
    defense: 87,
    avgPrice: 410,
    minPrice: 350,
    maxPrice: 480,
    lastPrice: 420,
    sellPriceMin: 205,
    sellPriceMax: 308,
    sellPriceMid: 256,
    salesCount: 34,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (1 * 86400000 + 1000 * 60 * 50)
  },
  {
    id: 'card_demo_17',
    boosterId: 'booster_demo_04',
    sessionId: 'session_demo_04',
    name: 'Colisée de Rome',
    rarity: 'R',
    rarityLabel: 'Rare',
    rarityShortCode: 'R',
    rarityColor: '#c6a7f2',
    cardIndex: 4,
    totalInBooster: 5,
    description: 'Amphithéâtre flavien grandiose achevé en 80 apr. J.-C., chef-d\'œuvre d\'ingénierie pouvant accueillir 65 000 spectateurs.',
    attack: 72,
    defense: 86,
    avgPrice: 240,
    minPrice: 200,
    maxPrice: 290,
    lastPrice: 250,
    sellPriceMin: 120,
    sellPriceMax: 180,
    sellPriceMid: 150,
    salesCount: 41,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (1 * 86400000 + 1000 * 60 * 49)
  },
  {
    id: 'card_demo_18',
    boosterId: 'booster_demo_04',
    sessionId: 'session_demo_04',
    name: 'Chouette Effraie',
    rarity: 'PC',
    rarityLabel: 'Peu Commune',
    rarityShortCode: 'PC',
    rarityColor: '#b1cff2',
    cardIndex: 3,
    totalInBooster: 5,
    description: 'Rapace nocturne au plumage soyeux et au disque facial en forme de cœur, chassant les rongeurs avec un vol totalement silencieux.',
    attack: 64,
    defense: 62,
    avgPrice: 70,
    minPrice: 55,
    maxPrice: 90,
    lastPrice: 65,
    sellPriceMin: 35,
    sellPriceMax: 53,
    sellPriceMid: 44,
    salesCount: 79,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (1 * 86400000 + 1000 * 60 * 48)
  },
  {
    id: 'card_demo_19',
    boosterId: 'booster_demo_04',
    sessionId: 'session_demo_04',
    name: 'Château de Versailles',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 2,
    totalInBooster: 5,
    description: 'Monument historique somptueux, résidence officielle des rois de France Louis XIV, Louis XV et Louis XVI.',
    attack: 38,
    defense: 60,
    avgPrice: 18,
    minPrice: 12,
    maxPrice: 25,
    lastPrice: 16,
    sellPriceMin: 9,
    sellPriceMax: 14,
    sellPriceMid: 11,
    salesCount: 220,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (1 * 86400000 + 1000 * 60 * 47)
  },
  {
    id: 'card_demo_20',
    boosterId: 'booster_demo_04',
    sessionId: 'session_demo_04',
    name: 'Volcan Vésuve',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 1,
    totalInBooster: 5,
    description: 'Sommet volcanique bordant la baie de Naples, tristement célèbre pour son éruption dévastatrice ayant enseveli Pompéi en 79.',
    attack: 45,
    defense: 40,
    avgPrice: 14,
    minPrice: 10,
    maxPrice: 20,
    lastPrice: 15,
    sellPriceMin: 7,
    sellPriceMax: 11,
    sellPriceMid: 9,
    salesCount: 260,
    hasRealMarketPrice: true,
    timestamp: Date.now() - (1 * 86400000 + 1000 * 60 * 46)
  },
  {
    id: 'card_demo_21',
    boosterId: 'booster_demo_05',
    sessionId: 'session_demo_05',
    name: 'Trou Noir Gargantua',
    rarity: 'L',
    rarityLabel: 'Légendaire',
    rarityShortCode: 'L',
    rarityColor: '#ffe144',
    cardIndex: 5,
    totalInBooster: 5,
    description: 'Objet céleste d\'une densité infinie dont le champ de gravitation empêche toute matière ou rayonnement électromagnétique de s\'échapper.',
    attack: 99,
    defense: 98,
    avgPrice: 4200,
    minPrice: 3900,
    maxPrice: 4900,
    lastPrice: 4350,
    sellPriceMin: 2100,
    sellPriceMax: 3150,
    sellPriceMid: 2625,
    salesCount: 5,
    hasRealMarketPrice: true,
    timestamp: Date.now() - 1000 * 60 * 12
  },
  {
    id: 'card_demo_22',
    boosterId: 'booster_demo_05',
    sessionId: 'session_demo_05',
    name: 'Stonehenge',
    rarity: 'R',
    rarityLabel: 'Rare',
    rarityShortCode: 'R',
    rarityColor: '#c6a7f2',
    cardIndex: 4,
    totalInBooster: 5,
    description: 'Monolithe mégalithique circulaire du néolithique situé dans le Wiltshire en Angleterre, aligné sur les solstices solaires.',
    attack: 54,
    defense: 86,
    avgPrice: 175,
    minPrice: 145,
    maxPrice: 215,
    lastPrice: 180,
    sellPriceMin: 88,
    sellPriceMax: 131,
    sellPriceMid: 109,
    salesCount: 61,
    hasRealMarketPrice: true,
    timestamp: Date.now() - 1000 * 60 * 11
  },
  {
    id: 'card_demo_23',
    boosterId: 'booster_demo_05',
    sessionId: 'session_demo_05',
    name: 'Mont Everest',
    rarity: 'PC',
    rarityLabel: 'Peu Commune',
    rarityShortCode: 'PC',
    rarityColor: '#b1cff2',
    cardIndex: 3,
    totalInBooster: 5,
    description: 'Plus haut sommet du monde culminant à 8 848 mètres d\'altitude dans la chaîne de l\'Himalaya entre le Népal et la Chine.',
    attack: 49,
    defense: 80,
    avgPrice: 48,
    minPrice: 38,
    maxPrice: 62,
    lastPrice: 45,
    sellPriceMin: 24,
    sellPriceMax: 36,
    sellPriceMid: 30,
    salesCount: 115,
    hasRealMarketPrice: true,
    timestamp: Date.now() - 1000 * 60 * 10
  },
  {
    id: 'card_demo_24',
    boosterId: 'booster_demo_05',
    sessionId: 'session_demo_05',
    name: 'Fosse des Mariannes',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 2,
    totalInBooster: 5,
    description: 'Fosse océanique la plus profonde du globe terrestre, atteignant environ 11 000 mètres sous le niveau de la mer.',
    attack: 40,
    defense: 58,
    avgPrice: 16,
    minPrice: 11,
    maxPrice: 22,
    lastPrice: 17,
    sellPriceMin: 8,
    sellPriceMax: 12,
    sellPriceMid: 10,
    salesCount: 240,
    hasRealMarketPrice: true,
    timestamp: Date.now() - 1000 * 60 * 9
  },
  {
    id: 'card_demo_25',
    boosterId: 'booster_demo_05',
    sessionId: 'session_demo_05',
    name: 'Nébuleuse d\'Orion',
    rarity: 'C',
    rarityLabel: 'Commune',
    rarityShortCode: 'C',
    rarityColor: '#b8f2d5',
    cardIndex: 1,
    totalInBooster: 5,
    description: 'Gigantesque nébuleuse diffuse en émission et réflexion au cœur de la constellation d\'Orion, berceau de pouponnières d\'étoiles.',
    attack: 46,
    defense: 52,
    avgPrice: 22,
    minPrice: 15,
    maxPrice: 30,
    lastPrice: 20,
    sellPriceMin: 11,
    sellPriceMax: 17,
    sellPriceMid: 14,
    salesCount: 190,
    hasRealMarketPrice: true,
    timestamp: Date.now() - 1000 * 60 * 8
  }
];

export const DEFAULT_DISCORD_CONFIG = {
  enabled: true,
  webhookUrl: 'https://discord.com/api/webhooks/123456789/wikimasters_secret_token',
  discordUserId: '345678901234567890',
  pauseThreadId: '987654321098765432',
  targetCardsList: ['Adèle Castillon', 'Trou Noir Gargantua', 'Léonard de Vinci'],
  rarityRoutingEnabled: true,
  priceRoutingEnabled: true,
  rarityThreads: {
    L: '110000000000000001',
    UR: '110000000000000002',
    SR: '110000000000000003',
    R: '110000000000000004',
    PC: '',
    C: ''
  },
  priceThreads: {
    tier1000: '220000000000000001',
    tier250: '220000000000000002',
    tier100: '220000000000000003',
    tier50: '',
    tier0: ''
  },
  minClickDelay: 1500,
  maxClickDelay: 2200,
  minBoosterWaitSec: 2.0,
  maxBoosterWaitSec: 4.0,
  humanCyclesEnabled: true,
  minActiveMin: 35,
  maxActiveMin: 50,
  minBreakMin: 10,
  maxBreakMin: 25
};

const SIMULATION_CARD_POOL = [
  { name: 'Nikola Tesla', rarity: 'UR', basePrice: 1350, atk: 88, def: 84, desc: 'Inventeur et ingénieur visionnaire d\'origine serbe, père du courant alternatif.' },
  { name: 'Hubble Deep Field', rarity: 'SR', basePrice: 470, atk: 65, def: 90, desc: 'Image emblématique de l\'espace profond révélant des milliers de galaxies lointaines.' },
  { name: 'Cleopâtre VII', rarity: 'UR', basePrice: 980, atk: 84, def: 78, desc: 'Dernière souveraine d\'Égypte de la dynastie ptolémaïque, reine légendaire.' },
  { name: 'Cité Interdite', rarity: 'SR', basePrice: 390, atk: 60, def: 92, desc: 'Palais impérial des dynasties Ming et Qing au cœur de Pékin.' },
  { name: 'Charles Darwin', rarity: 'R', basePrice: 170, atk: 66, def: 74, desc: 'Naturaliste anglais à l\'origine de la théorie moderne de l\'évolution des espèces.' },
  { name: 'Aurora Australis', rarity: 'R', basePrice: 155, atk: 55, def: 82, desc: 'Aurore australe brillante illuminant le ciel de l\'hémisphère sud.' },
  { name: 'Panthéon de Rome', rarity: 'PC', basePrice: 42, atk: 44, def: 70, desc: 'Temple antique romain surmonté d\'une gigantesque coupole en béton non armé.' },
  { name: 'Mont Fuji', rarity: 'PC', basePrice: 48, atk: 50, def: 68, desc: 'Stratovolcan sacré du Japon culminant à 3 776 mètres d\'altitude.' },
  { name: 'Canal de Panama', rarity: 'C', basePrice: 18, atk: 35, def: 55, desc: 'Voie navigable artificielle de 80 km reliant l\'océan Atlantique à l\'océan Pacifique.' },
  { name: 'Désert du Sahara', rarity: 'C', basePrice: 15, atk: 40, def: 45, desc: 'Plus vaste désert chaud de la planète couvrant le tiers nord de l\'Afrique.' },
  { name: 'Isaac Newton', rarity: 'L', basePrice: 3400, atk: 93, def: 95, desc: 'Mathématicien et physicien anglais ayant formulé les lois universelles de la gravitation.' }
];

/**
 * Génère un tirage aléatoire réaliste pour la simulation continue
 */
export function generateRandomSimulationCard(boosterIndex = 1) {
  const item = SIMULATION_CARD_POOL[Math.floor(Math.random() * SIMULATION_CARD_POOL.length)];
  const rarityMeta = OFFICIAL_RARITIES[item.rarity] || OFFICIAL_RARITIES.C;
  const variance = (Math.random() * 0.3) - 0.15; // +/- 15%
  const avgPrice = Math.round(item.basePrice * (1 + variance));
  const minPrice = Math.round(avgPrice * 0.85);
  const maxPrice = Math.round(avgPrice * 1.2);
  const lastPrice = Math.round(avgPrice * (1 + (Math.random() * 0.1 - 0.05)));

  return {
    id: `card_sim_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
    boosterId: `booster_sim_${Math.floor(Date.now() / 15000)}`,
    sessionId: `session_sim`,
    name: item.name,
    rarity: item.rarity,
    rarityLabel: rarityMeta.label,
    rarityShortCode: rarityMeta.shortCode,
    rarityColor: rarityMeta.color,
    cardIndex: ((boosterIndex - 1) % 5) + 1,
    totalInBooster: 5,
    description: item.desc,
    attack: item.atk,
    defense: item.def,
    avgPrice: avgPrice,
    minPrice: minPrice,
    maxPrice: maxPrice,
    lastPrice: lastPrice,
    sellPriceMin: Math.round(avgPrice * 0.50),
    sellPriceMax: Math.round(avgPrice * 0.75),
    sellPriceMid: Math.round(avgPrice * 0.625),
    salesCount: Math.floor(Math.random() * 80) + 5,
    hasRealMarketPrice: true,
    timestamp: Date.now()
  };
}
